### PR TITLE
PostgreSQL support: both backend and authentication/authorization

### PR DESCRIPTION
**Pull request by ppentchev**
Hi,

Thanks for maintaining and developing NagVis!

The rumours about phasing out the livestatus socket support do not leave many viable choices for Icinga + NagVis installations where Icinga uses a PostgreSQL database and not a MySQL one.  So what do you think about the attached commits that provide some basic direct PostgreSQL support, both for authentication and for the actual backend querying the Icinga data?

This implementation will very soon be tested and deployed at a production installation with a couple of hundred hosts and various service checks for them (both basic ones like ping and high-level comprehensive semantic application-specific service operation checks).  Understandably, the customer would prefer that the changes make their way into the actual NagVis distribution at some point soon, so that we don't have to maintain a fork (albeit an almost trivial one so far); thus, let me know what you think about the idea of PostgreSQL support and, if you like it, the chances of this particular implementation being merged :)

Right now, the PostgreSQL handler and the two classes that use it are almost a line-by-line port of the MySQL code.  I have some work in progress that introduces prepared statements (even if only for security, but sometimes there might be performance improvements, too) and I'm also thinking about investigating the possibility of using PDO for all three database backends - SQLite, MySQL, and now PostgreSQL.  Of course, with PDO the table creation code would have to be different, and there are some slight variations in the SQL syntax, hence the "investigation" part.  But, for the present, this should be enough to get a PostgreSQL backend going.

Thanks in advance for taking the time to look at this; please let me know if you have any comments, misgivings or such, and keep up the great work!

G'luck,
Peter

PS. I have not touched the copyright statements, since most of the code is still based on the MySQL implementations; however, I would be ready to step in to maintain the PostgreSQL code to whatever extend the developers consider it necessary.  Also, I have not updated the localization files, but this would be trivial to do in a follow-up commit; let me know if I should do it, or maybe this should come after the main idea of a PostgreSQL implementation has been discussed.

### CODE REVIEW

**Comment by LarsMichelsen** [comment]
Hi Peter,

first: Thanks for your contribution and the work you have already done. I do really appreciate that!

I am not really up-to-date with the things that are happening in the Icinga universe. What I already felt is that the Livestatus implementation was not in the scope of the developers (see https://github.com/Icinga/icinga2/issues/1970). Seems like NagVis was the only tool using this.
So I am not surprised about such "rumors".

From the NagVis point of view it's a bit sad, because the Livestatus thing has been a nice cross core compatible way to access monitoring data with only small administrative and performance overhead. I don't know anything about the performance of the Icinga 2 Livestatus implementation, but for other cores it was always a fast thing. Whatever, a not maintained API is a bad API, so in the long term it will be better to use a supported one.

I am happy that there are APIs to access the relevant data in current monitoring cores. We should use them.

To clarify things: I am not using the MySQL backend at all and I am not able to support it in my limited time. That applies to the PostgeSQL backend too. If you like to do it, you're welcome!

Now I got some questions on your changes:

a) NagVis is using SQLite for the internal auth database. There was a time were some enterprise distros had no SQLite support for PHP, that is why the MySQL auth code has been written. But it was rarely used. From my point of view all users should stick with the default SQLite auth DB when not integrating with 3rd party user/permission databases. Now what's the point of your Postgres auth DB code? Is it some kind of integration with Icinga or is it just a port of the MySQL stuff? In later case I would prefer to not integrate that and stick with the SQLite user db. Mainly for simplicity.

b) Icinga 2 seems to support both, MySQL and PostgreSQL. What is the recommended or most used engine?

c) I guess the Icinga 2 MySQL and PostgreSQL database schemes are nearly equal. Wouldn't it make sense to make NagVis to support both? Maybe the database engine specific things can be abstracted that we can implement a single backend which can be changed with an option to either use MySQL oder PostgreSQL. Or, alternatively, provide two backends that share a common code base.

I have something in my mind were there is no need for copy-n-paste in case something like the SQL scheme changes. It could really help to reduce fragmentation here.

Do you think that you could implement it in such a way?

**Comment by LarsMichelsen** [comment]
Any updates on this?

**Comment by ppentchev** [comment]
Hi,

Sorry about that; I did intend to send you an update yesterday or the day before, but other things happened.

The reason we started writing a PostgreSQL backend for NagVis at all was not just the livesocket going away, but also its being a bit buggy, as you should be well aware (aggregation and stuff) :)  Other than that, 

a) You're absolutely right here, the only reason for writing the PostgreSQL auth code was that I rewrote everything that used MySQL for PostgreSQL.  There's no pressing need for that, but see below about the PDO (and about the locking problems, too).

b) PostgreSQL is actually well-supported and a first-class citizen in the Icinga world; I can't quote exact numbers, but there are quite a lot of people who use it.  Sorry, I can't give you anything more specific, but it seems reasonable to me to suport it, if it's not too much effort - and, as stated before, I'm prepared to share this effort.

c) Right, part of the reason that I've not replied for a week was that I delved into writing a backend using PHP's PDO database abstraction framework.  It turned out to be mostly straightforward; once MySQL is put into its so-called PostgreSQL compatibility SQL mode, the SQL syntax is almost the same and it's trivial to rewrite some queries dynamically.  However, the reason that I didn't let you know about that was some kind of locking problem that I ran into using SQLite through PDO on my Debian system; I still haven't quite got to the bottom of it, but for the present it won't let me use the PDO backend for authentication against a SQLite database.  I should be able to solve this in the next couple of days, then I'll give you some real code.

Thanks a lot for your interest and for your ideas and understanding!

G'luck,
Peter

PS. On a mostly unrelated note, are you aware of the GitHub Terms of Service controversy as described in https://www.mirbsd.org/permalinks/wlog-10_e20170301-tg.htm#e20170301-tg_wlog-10#e20170301-tg_wlog-10 ?

**Comment by LarsMichelsen** [comment]
Sounds great. I am looking forward to take a look at your changes.

Best regards
Lars

**Comment by ppentchev** [comment]
Hi,

Sorry for the delay, these were a long "couple of days".  Here is the next iteration of the PostgreSQL support commits, or, should I say, the first iteration of the PDO (PHP Data Objects) migration.  I hope that these changes are not too much - most of them are actually almost mechanical, but they do change several things in how NagVis interacts with the databases:

1. There is a CorePDOHandler class now that pretty much handles all the actual database queries.  It has a $DRIVERS array that contains both driver-specific information and actual SQL queries, see below.

2. The SQL queries were moved out of the functions that use them and into a common array; this was done mainly to keep possible changes between SQL engines to a minimum.  Later, it turned out that there were no actual changes needed for the vast majority of the queries, but still I thought I'd move the rest there, too.

3. The query() method of the DB object (the CorePDOHandler object) now accepts either a query name to look up in the $DRIVERS array, or a full text (if the name is not found in the array, the string is assumed to be the full text of the query).  It also accepts an associative array of parameters, used in most of the queries.

4. The syntax of most of the queries was changed slightly so that they may be executed on SQLite, MySQL (with a twist), and PostgreSQL with no syntax modifications.  The main change is that if a field name needs to be quoted, it is placed in double quotes now, not in backticks as in the MySQL syntax.  The other change is that any names that coincide with reserved words (such as perms.mod) and any names that need their uppercase/lowercase letters preserved (such as permId, userId, and roleId) are quoted now; the rest are left unquoted.  The uppercase/lowercase change is needed for PostgreSQL compatibility, although, as discussed before, the authentication/authorization classes do not need to support PostgreSQL at all..... if the quoting of the userId, roleId, and permId fields looks too ugly to you, I could revert that and just hope that no one tries to run in on a PostgreSQL database :)

5. To support the PostgreSQL style of quoting field names with double quotes, the MySQL driver now issues an additional "SET SESSION sql_mode = 'postgresql'" query at the start; that turns out to be enough.

6. The remaining syntax difference between the SQL engines is the operator used for regular expression matching - PostgreSQL uses "~" and "!~", SQLite uses "REGEXP" and "NOT REGEXP", MySQL also uses "REGEXP", but for historical reasons NagVis seems to use "REGEXP BINARY" to avoid collation problems, I suppose.  Thus, the $DRIVERS array now also defines this operator for each driver, and the GlobalBackendPDO class uses it in the filtering functions.

So, uhm, yeah... thanks for reading this far, I guess, and hope you're not totally scared off by the extensive changes :)  Of course, pretty much everything is open to discussion, and you have the final word in all the decisions.  Still - and I do realize how strange this sounds, and I do apologize for saying this after two weeks of silent development - the customers that I mentioned in my first message and I would be very grateful for any feedback, and any idea of how you see the chances of this actually making its way into NagVis in this form or something close to that.  Sorry again for getting carried away with rewriting stuff and not letting you know anything in the meantime!

Thanks for your patience, thanks in advance for your time in reviewing this, and keep up the great work!

G'luck,
Peter

**Comment by ibrewster** [comment]
How usable is this in it's current sate, if I were to check out the fork containing these changes? I'm running icinga2 with a PostgreSQL backend, and was wanting to put up a nagviz based status board, but from what I can tell right now, with the live status backend, the system is simply too buggy to be useful.

**Comment by ppentchev** [comment]
Well, it has not been deployed in production yet, but a test deployment seems to be working fine - and, no, it should not have the Icinga livesocket bugs.  If you could test the current tip of the pull request - https://github.com/ppentchev/nagvis/commit/b8d6491e557a9c4d3e922982670a9dc68e25eb03 - configure a backend with type "pgsql" and the proper database authentication settings, and let me know if it works for you, I'd be very grateful!

G'luck,
Peter

**Comment by LarsMichelsen** [comment]
Oh, wow. The diffs are huge ;-) I'll need some time...

**Comment by ibrewster** [comment]
Well, with the caveat that I don't really understand PHP very well, my first attempt gave me this:

`Error: (0) Array to string conversion
URL: /nagvis-git/frontend/nagvis-js/index.php
File: /var/www/nagvis-git/share/server/core/classes/CorePDOHandler.php
Line: 437
#0 /var/www/nagvis-git/share/server/core/classes/CorePDOHandler.php(437): nagvisExceptionErrorHandler(8, 'Array to string...', '/var/www/nagvis...', 437, Array)
#1 /var/www/nagvis-git/share/server/core/classes/CoreAuthModPDO.php(68): CorePDOHandler->updateDb()
#2 /var/www/nagvis-git/share/server/core/classes/CoreAuthHandler.php(47): CoreAuthModPDO->__construct()
#3 /var/www/nagvis-git/share/server/core/functions/index.php(44): CoreAuthHandler->__construct()
#4 /var/www/nagvis-git/share/frontend/nagvis-js/index.php(53): require('/var/www/nagvis...')
#5 {main}`

...which I was able to work around by changing line 437 to this (which may or may not be an appropriate fix, but did silence the error):

`$reason = "Could not update the database to version $ver: '".$q[1]."'"`

Now I get the following:

`Could not execute the -create-auth-users query: HY000( 1): near "-": syntax error`

...Apparently called from the createInitialDb function. Might this have something to do with the earlier discussion about using sqlite for the internal auth database? Dunno. That's as far as I got.

P.S. Are the comments here the appropriate place for this, or should we take this discussion somewhere else?

**Comment by ppentchev** [comment]
Aaaahhh, right... I'm really, really sorry about this - about both of these!  The first one was a stupid case of testing a change, then making *another* change and not testing the error path afterwards - yes, the name of the query to run for the update, $q[0], is the right thing to show in the error message.  The second one... well, I plain forgot to migrate the SQLite queries for creating the NagVis-specific auth database!

Could you try https://github.com/ppentchev/nagvis/commit/7d9a611128e3b9c98d25faf0f167d7a14c72749a now?  Thanks a lot for testing this and for your patience with me! :)

G'luck,
Peter

**Comment by ibrewster** [comment]
That looks better :-).  Other than the incessant lags and timeouts I'm getting when trying to do *anything* (for example, I have yet to be able to change the default password on the admin account), things appear to be working. I was able to set up a map with multiple hostgroups (which I couldn't do successfully with the live status backend), and a second map containing a mixture of hosts, groups, and maps also appears to be working.

One oddity that I was was hoping would go away, however, appears to still remain, which may indicate something wrong with my setup rather than an issue with your code: I have at least one host that is showing "25" services in the "summary output" line of the popup, when in fact it only has 3 services (and only shows three in the service section of the popup). If I add another instance of the same object, it now only shows the proper 3 services - but it shows the host state as "unchecked" and the services as "pending". Of course, viewing the same host in the icinga2 web interface shows it fine. So I'm not sure where the fault lies there, but apparently there is a fault, and it is exhibited both in the Postgresql backend and the livestatus backend, but not the icinga2 web interface. I may try deleting the host from icinga completely and re-adding it, just to see if that helps.

**Comment by ppentchev** [comment]
OK, so I was not the only one experiencing the timeouts...  It seems that the SQLite3 driver managed to deadlock against itself (well, okay, another thread of the PHP interpreter, but, all the same, a bit weird).  Fortunately, after spending a couple of hours trying to fight it in different ways, it turned out that the fix was really simple - if you update your sources to https://github.com/NagVis/nagvis/pull/90/commits/187e2026d30d3e7d8db3fcad703f07977374753e this will probably go away.  Sorry, I know how exasperating it must have been, that's why I switched to the MySQL auth database during development...

About the number of services - grrr, so it seems that switching from the livestatus socket to the PostgreSQL database did not fix this particular bug after all.  I'm looking into it now.  BTW, did you delete the host definition?  Did it help?  Can you still reproduce the bug?  If you can, would it be possible for you to send me a pg_dump of Icinga's database so I can reproduce it easier?  Of course, it's fine if you obfuscate/remove some of the information, but it would be great to have something to start from (although I'll probably be able to reproduce it myself given a bit of time).

G'luck,
Peter

**Comment by ibrewster** [comment]
Yeah, much better - the web interface is usable again :) Regarding the service count, I think what may have happened there is that when I copied my maps from my old config, the backend_id may have been specified on the individual object, such that simply changing the backend for the *map* didn't change the backend for the object. Thus the change in behavior when I deleted and re-added it. That said, the new behavior is showing the correct number of services, but showing them all (and the host) as pending/unchecked (but still OK on the summary line - go figure), so that's only marginally better :-) 

I tried giving the host where I was seeing the issues a different name, so icinga would treat it as a new host, but that didn't seem to make any difference after I added the "new" host on the map. Apparently there is *something* about that host it doesn't like.

I can do a pg_dump, but I think I'd rather send it just to you rather than posting it here for all the world to see :-)

**Comment by ibrewster** [comment]
Ok, scratch everything I've said (ok, maybe not *everything*). Turns out when I looked at the actual map definition, *all* the hosts I had on the map had the backend ID specified as the livestatus backend. Once I went through and removed that, now all the hosts show up with the correct summary information, and the correct list of services, but with the `state` listed as pending/unchecked. Weird.
screen shot 2017-03-28 at 1 36 38 pm

**Comment by ibrewster** [comment]
I believe I have tracked down the host display problem. In the GlobalBackendPDO.php file, line 531, there is the statement:

` if($data['has_been_checked'] == '0' || $data['current_state'] == ''){`

...but *apparently* in php, '' is equal to '0' - maybe because both are considered to be false? In any event, the result is that whenever the host is up, it is marked as "unchecked", since that matches. A simple modification to:

`if($data['has_been_checked'] == '0' || $data['current_state'] === '') {`

appears to fix the issue, although I don't know 100% it would still have the desired effect (are you truly looking for an empty string, or just anything "falsy"?)

Presumably the issue with the service status is the same sort of thing, though I haven't checked that yet.

**Comment by LarsMichelsen** [comment]
I had a quick (sorry, less time at the moment) look at the changes. As stated before, these huge commits with several renamed files and changes in the files in the same commit will be hard to review. Separated commits for renamed files or moved functions and other code changes would be easier to track.

For the moment I have the following questions:

a) You abstracted the auth database to PDO, fine. It is now possible to use SQLite (default), MySQL and PostgreSQL. For the first both we already have configuration options. But how to configure the new one?

b) The worldmap was only usable with SQLite. You abstracted it to use the PDO module now, right? Is the abstraction the only step or is it already usable with MySQL/PostgreSQL? If so, how to configure it?

c) For all of the NagVis specific features (auth, worldmap), if you configure the DB correctly, are the tables automatically initialized on first use?

d) In the changes I made in the last months I removed the "copyright/author" comments from the functions/classes, because they are useless. If you want to know the author "git blame" is your friend. Please drop the Author comments from the new/changed code. The comments should be useful and explain things that are not obvious in the code. Meaning a comment should describe "why" instead of "what". 

Todos I see at the moment:

1. Update the documentation (New main config options, new dependencies (PHP PDO, ...), new backend).
2. Update the installer (check/verify PHP PDO, similar to other modules)

**Comment by ppentchev** [comment]
To Israel:  Argh, sorry, this was yet another one of those "how the *bleep* did I not see this while testing?!" moments.  However, this one will be a bit harder to fix, I'll think about it a bit more later this evening; the problem is that the MySQL PDO driver for PHP does things a bit too closely to the C API interface for MySQL and returns *all* values as *strings*, no matter what their underlying database type is.  The PostgreSQL driver returns integers as PHP integers.  The NagVis code was written to accomodate strings, and, yeah, your analysis is completely correct from that point on.  I'll figure out a way to fix it, and also look for other such problems.  Sorry!

To Lars: thanks for the preliminary look at the code!  Now, about your four questions:

a) Well, I dropped the idea of a PostgreSQL authentication database since you convinced me that it is not really needed at this point in time; thus, I have not provided a CoreAuthModPgSQL or CoreAuthorisationModPgSQL or similar.  Those would be trivial to write (basically copy the MySQL ones and fix the DSN), and the configuration would also be trivial to add, but if you think that they're missing from the current patch, that's because they are indeed not there :)  If you want me to, I could do that, but I was under the impression that you'd rather not have that.

b) The only reason I abstracted the worldmap to use the PDO module was that it was using the existing CoreSQLiteHandler and, well, it was kind of removed, so I had to adapt the worldmap to keep it working.  Just as with authentication/authorisation, I did not plan on supporting different database backends for the worldmap.  Again, if you want me to, I can do that.

c) Yes, the tables creation is done as before, although abstracted a bit in the CorePDOHandler::$DRIVERS array - at least for the authn/authz tables; the worldmap still creates the tables in its own class.  Of course, if the worldmap should be made to support other databases, then the creation might also need to be done a bit differently; not difficult, just a bit more to do.

d) OK, I will do that in the next version of the patch (once I figure out how to fix the string/integer problem discussed with Israel).

About the todos: well, as explained above, there are no main config options.  Okay, so there is the new 'pgsql' backend to be used for the maps; sure, I can find where this is documented and add it.  Ahhh, the installer... yeah, the installer... OK, I'll think about that, too.

Thanks again for considering this and for looking at it!

G'luck,
Peter

**Comment by ibrewster** [comment]
No problem - that's what having other people testing is all about! I was thinking, if simply replacing the `==` with `===` causes problems with not enough being matched, perhaps something like:

`if($data['has_been_checked'] == '0' || ($data['current_state'] =='' && $data['current_state']!==0) ) {`

to simply exclude an integer zero from the match while leaving all else as-is would work better, both for the host status and the service status (which I did find, BTW, and it appears to be the same)? Of course, there may still other occurrences of the same sort of issue that haven't been found yet.

**Comment by LarsMichelsen** [comment]
a) That's fine.

b) Same here.

To summarize both things: I don't see any benefit in supporting different database engines for the internal data storage of NagVis. Let's stick with SQLite here.

c) Good.

Looking forward to your next patch.

**Comment by ppentchev** [comment]
Israel, could you try https://github.com/NagVis/nagvis/pull/90/commits/6d88c1abec790d194acfb8338776d446125eb6c4 and see if it works better for you?

G'luck,
Peter

**Comment by ibrewster** [comment]
Close, but not quite. Now the services list on any given host shows the correct state, but says downtime (see attachment). Sorry :-)

Just out of curiosity, and for my education in PHP, I noticed you fixed the string/int issue with what looks to be a *relatively* complex function. Why that approach rather than just going with `<whatever>===''` or `... && <whatever>!==0`? Presumably your function catches something that the others miss, but what?

screen shot 2017-03-30 at 8 16 44 am

**Comment by ppentchev** [comment]
Argh.  One of these days I'm going to learn to check *every* part of a change I make :(  Sorry about that; https://github.com/NagVis/nagvis/pull/90/commits/8a72227f5328700a78ea4429b3068b1867522807 should fix it.

As to the functions part, well, I strongly believe in breaking often-used code into functions for three reasons: easier to type, harder to mess up, and much, much easier to change everywhere without missing a piece when something needs to be changed.  Of course, right now I demonstrated that the "harder to mess up" part is not absolute - sometimes converting a written-out logical check to a function call can be done, well, backwards :(

G'luck,
Peter

**Comment by ibrewster** [comment]
There we go. Now it looks good. Are we supposed to see a list of hosts in the popup for a hostgroup, similar to the popup for a map? I don't recall the previous behavior, since host groups were one of the things that never did work properly with the livestatus backend.

Re: functions, yeah, that's generally a good idea when you are using the same code. I guess I just don't generally run into if statements where I'm testing the same thing often enough to bother :-)

**Comment by LarsMichelsen** [comment]
@ibrewster You should see hosts in host group hover menus and services in service group hover menus. Just like you see services for host objects. It works with livestatus backend in general, but not with Icinga 2.

**Comment by LarsMichelsen** [comment]
@ppentchev 

I now had a look at all of your commits. The code looks fine.

What we need to do now:

a) The documentation has to be written / copied (docs/en_US/backend_*.html).
b) The installer thing is still open and I want to check the major distributions whether or not PHP supports PDO with or without installing additional packages.
c) Announce the change and publish a new release.

I'll care about the tasks b) and c) in the next days. Would be nice if you could help me out with a).

**Comment by ibrewster** [comment]
Ok, if I should be seeing a list of hosts in the host group popup, then that remains as a bug in this patch - albeit one I can stomach, given that host groups really didn't work at all with the live status backend :-)

**Comment by ppentchev** [comment]
Hi, and sorry again for the longish delay :(  The truth is, i tried to break up the initial commit into two parts: first use prepared queries in all the DB drivers (with a common array for the queries' SQL text), then bring them all in to use PDO.  However, it turned out that this is not so easy, since the "mysql" (not "mysqli") PHP extension used by the authentication and authorization MySQL module does not really support prepared queries.  Of course, it would've been possible to first convert the authn/authz MySQL modules to use mysqli like the ndomy backend, but then that would've been one more mostly-mechanical change (use the mysqli_* functions instead of mysql_*) just to make another mostly-mechanical change (use mysqli_prepare() and the predefeined query "names") afterwards, only to be subsumed into a change that is already done (use prepared queries and PDO in one change)...  Sure, I could do that, but it does not seem worth it to me; let me know if you'd like it done this way anyway.

I just pushed another commit with a simple documentation for the PostgreSQL backend.  I copied it from the MySQL (ndomy) backend one, but then removed the ndoutils and ndo2db references; although there have been people who have tried to use ndoutils with PostgreSQL, at least a quick look at the sources of ndoutils-1.4 did not convince me that ndoutils (and ndo2db) really supports PostgreSQL, so I just omitted those references.

About the installer, it seems to me that recent versions of PHP, at least on Debian- and RedHat-derived Linux distributions, bundle the PDO support for MySQL and PostgreSQL right into the php-mysql and php-pgsql packages, so no additional OS packages ought to be needed.  However, there is another problem: in Debian testing/unstable, the packaging of PHP has been changed a bit, and the PHP version in the package name is now major.minor, e.g. php7.0-pgsql instead of the php5-pgsql package in the earlier releases.  Thus, the dpkg -l "php[0-9]-$MOD" command that check_php_modules() uses shall not really work, since php7.0 does not match php[0-9] :(  It might be made to work with just "php*-$MOD" or something like that, but of course this might produce false positives, altough I did not find any with a couple of quick dpkg -l and apt-cache search -n commands for all of the modules that install.sh actually checks for.  But all of this is almost of no consequence, since the check_php_modules() function tries to find the module in other ways afterwards, it works - at least on my Debian testing system with php7.0-* packages.

**Comment by LarsMichelsen** [comment]
Okay. Let's proceed with this. I'll merge it now and test it a bit. In case it looks good I'll publish a new release in the next days.

Thanks a lot for your contribution!

**Comment by ibrewster** [comment]
Just FYI, I just ran into another issue. When trying to create an automap, I get the following error:

`Fatal error: Call to a member function fetch() on boolean in /var/www/nagvis-git/share/server/core/classes/GlobalBackendPDO.php on line 1095`

**Comment by ppentchev** [comment]
Hi,

Sorry about that!  Could you take a look at https://github.com/NagVis/nagvis/pull/99 and see if it fixes the problem?

G'luck,
Peter

**Comment by ibrewster** [comment]
Looks good for the automap. So that just leaves the missing host list when hovering over a hostgroup (unless that's just me)
screen shot 2017-04-12 at 11 28 19 am

**Pull request merged**
